# Generated by Django 2.0.4 on 2018-05-29 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deliverydetail',
            old_name='serial',
            new_name='delivery',
        ),
        migrations.RenameField(
            model_name='entrydetail',
            old_name='serial',
            new_name='entry',
        ),
        migrations.RenameField(
            model_name='purchasedetail',
            old_name='serial',
            new_name='purchase',
        ),
    ]
