# Generated by Django 2.0.4 on 2018-05-29 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0002_auto_20180529_1813'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasedetail',
            name='left',
            field=models.IntegerField(default=0),
        ),
    ]
