# Generated by Django 2.0.4 on 2018-05-30 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0004_auto_20180530_2005'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='term',
            field=models.DateTimeField(null=True),
        ),
    ]
