# Generated by Django 2.0.4 on 2018-05-14 05:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foreground', '0006_auto_20180514_1111'),
        ('kitchen', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Capacity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.FloatField()),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foreground.Food')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kitchen.Station')),
            ],
        ),
        migrations.AddField(
            model_name='station',
            name='foods',
            field=models.ManyToManyField(through='kitchen.Capacity', to='foreground.Food'),
        ),
    ]
