# Generated by Django 2.0.4 on 2018-05-16 00:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foreground', '0007_food_available'),
        ('kitchen', '0002_auto_20180514_1335'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prepare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField()),
                ('date', models.TimeField()),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foreground.Food')),
            ],
        ),
    ]
