# Generated by Django 2.0.4 on 2018-05-16 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0004_auto_20180516_0930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prepare',
            name='date',
            field=models.TimeField(auto_now=True),
        ),
    ]
