# Generated by Django 2.0.4 on 2018-05-30 11:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import personnel.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('personnel', '0002_auto_20180514_2040'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='account',
            field=models.ForeignKey(default=personnel.models.get_temp_user, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
