# Generated by Django 2.0.6 on 2018-06-28 12:54

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import personnel.models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0003_employee_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='performance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logTime', models.DateTimeField(default='2018-06-01 23:40:22.814392')),
                ('bonus', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('penalty', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('reason', models.TextField(default='原因如下：', validators=[django.core.validators.MaxLengthValidator(1000)])),
            ],
        ),
        migrations.RemoveField(
            model_name='distribute',
            name='job',
        ),
        migrations.RemoveField(
            model_name='distribute',
            name='period',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='performance',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='salary',
        ),
        migrations.RemoveField(
            model_name='salary',
            name='name',
        ),
        migrations.AddField(
            model_name='distribute',
            name='end_work_hour',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='distribute',
            name='eventType',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='distribute',
            name='start_work_hour',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='distribute',
            name='work_date',
            field=models.CharField(default='2017/02/15', max_length=15),
        ),
        migrations.AddField(
            model_name='distribute',
            name='workingTime',
            field=models.CharField(blank=True, default='2hours', max_length=10, null=True, verbose_name='工作总时间'),
        ),
        migrations.AddField(
            model_name='employee',
            name='age',
            field=models.IntegerField(default=18, verbose_name='年龄'),
        ),
        migrations.AddField(
            model_name='employee',
            name='bankCard',
            field=models.CharField(default='1234567890123456789', max_length=30, verbose_name='银行卡号'),
        ),
        migrations.AddField(
            model_name='employee',
            name='department',
            field=models.CharField(default='厨房', max_length=64, verbose_name='部门'),
        ),
        migrations.AddField(
            model_name='employee',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='邮箱'),
        ),
        migrations.AddField(
            model_name='employee',
            name='entryTime',
            field=models.CharField(default='2017/02/15', max_length=20, verbose_name='入职时间'),
        ),
        migrations.AddField(
            model_name='employee',
            name='ethnic',
            field=models.CharField(default='汉族', max_length=50, verbose_name='民族'),
        ),
        migrations.AddField(
            model_name='employee',
            name='gender',
            field=models.CharField(default='男', max_length=8, verbose_name='性别'),
        ),
        migrations.AddField(
            model_name='employee',
            name='idCardNum',
            field=models.CharField(default='370401199702135689', max_length=18, verbose_name='身份证号'),
        ),
        migrations.AddField(
            model_name='employee',
            name='iswork',
            field=models.CharField(default='是', max_length=8),
        ),
        migrations.AddField(
            model_name='employee',
            name='personPhoto',
            field=models.ImageField(blank=True, null=True, upload_to='staff_Photo'),
        ),
        migrations.AddField(
            model_name='employee',
            name='position',
            field=models.CharField(blank=True, default='员工', max_length=80, null=True, verbose_name='职位'),
        ),
        migrations.AddField(
            model_name='employee',
            name='staffId',
            field=models.CharField(blank=True, max_length=9, null=True, verbose_name='员工工号'),
        ),
        migrations.AddField(
            model_name='salary',
            name='baseWage',
            field=models.DecimalField(blank=True, decimal_places=2, default='2000', max_digits=16, null=True, verbose_name='基本工资'),
        ),
        migrations.AddField(
            model_name='salary',
            name='employee',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='personnel.Employee'),
        ),
        migrations.AddField(
            model_name='salary',
            name='releaseDate',
            field=models.DateTimeField(default='2018-06-01 23:40:22.814392'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='account',
            field=models.ForeignKey(default=personnel.models.get_temp_user, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='登陆账号'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='employee',
            name='name',
            field=models.CharField(default='Zhao', max_length=32, verbose_name='姓名'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone',
            field=models.CharField(default='18800209387', max_length=16, verbose_name='联系电话'),
        ),
        migrations.AlterField(
            model_name='salary',
            name='salary',
            field=models.DecimalField(blank=True, decimal_places=2, default='3200', max_digits=16, null=True, verbose_name='工资'),
        ),
        migrations.AddField(
            model_name='performance',
            name='employee',
            field=models.ForeignKey(default='30', on_delete=django.db.models.deletion.CASCADE, to='personnel.Employee'),
        ),
    ]
