# Generated by Django 2.0.6 on 2018-06-29 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0004_auto_20180628_1254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='distribute',
            name='work_date',
        ),
    ]
