# Generated by Django 2.0.6 on 2018-06-29 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0005_remove_distribute_work_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='distribute',
            name='workingTime',
        ),
    ]
