# Generated by Django 2.0.6 on 2018-07-02 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0006_remove_distribute_workingtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='salary',
            name='checkstatus',
            field=models.BooleanField(default=False),
        ),
    ]
