# Generated by Django 2.0.6 on 2018-07-02 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='total',
            name='fromId',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
