# Generated by Django 2.0.6 on 2018-07-02 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0002_total_fromid'),
    ]

    operations = [
        migrations.AddField(
            model_name='total',
            name='marks',
            field=models.CharField(blank=True, max_length=4096, null=True),
        ),
    ]
