# Generated by Django 2.0.4 on 2018-05-07 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foreground', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='describe',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
