# Generated by Django 2.0.4 on 2018-05-08 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foreground', '0002_auto_20180507_2336'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.CharField(blank=True, max_length=300, null=True)),
                ('state', models.TimeField()),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foreground.Food')),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='state',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AddField(
            model_name='detail',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foreground.Order'),
        ),
    ]
