# Generated by Django 2.0.4 on 2018-05-08 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foreground', '0003_auto_20180508_1726'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='foods',
        ),
    ]
