# Generated by Django 2.0.4 on 2018-05-08 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foreground', '0004_remove_order_foods'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='foods',
            field=models.ManyToManyField(through='foreground.Detail', to='foreground.Food'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.TimeField(auto_now=True),
        ),
    ]
