# Generated by Django 2.0.4 on 2018-05-16 01:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0004_auto_20180516_0930'),
        ('foreground', '0007_food_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail',
            name='station',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='kitchen.Station'),
            preserve_default=False,
        ),
    ]
