# Generated by Django 2.0.4 on 2018-05-21 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foreground', '0009_auto_20180520_0225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
