# Generated by Django 2.0.4 on 2018-05-27 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foreground', '0010_auto_20180521_2326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
