# Generated by Django 2.0.4 on 2018-05-29 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0001_initial'),
        ('foreground', '0012_food_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='material',
            field=models.ManyToManyField(through='warehouse.Bom', to='warehouse.Material'),
        ),
    ]
