# Generated by Django 2.0.6 on 2018-07-02 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foreground', '0013_food_material'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='checked',
            field=models.BooleanField(default=False),
        ),
    ]
